from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, EmailStr
from database.firebase import get_firestore
from passlib.context import CryptContext
from datetime import datetime, timedelta
import jwt
import os
import uuid

router = APIRouter()

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
SECRET_KEY = os.getenv("JWT_SECRET", "supersecretkeyedusense")
ALGORITHM = "HS256"

class LoginSchema(BaseModel):
    email: str
    password: str

class SignupSchema(BaseModel):
    name: str
    email: EmailStr
    password: str
    role: str = "student"

def verify_password(plain_password, hashed_password):
    return pwd_context.verify(plain_password, hashed_password)

def get_password_hash(password):
    return pwd_context.hash(password)

def create_access_token(data: dict):
    to_encode = data.copy()
    expire = datetime.utcnow() + timedelta(minutes=1440)
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
    return encoded_jwt

# Demo accounts for testing (no database needed)
DEMO_ACCOUNTS = {
    "admin@edusense.com": {"password": "admin123", "role": "admin", "name": "Admin User", "id": "ADMIN_001"},
    "faculty@edusense.com": {"password": "faculty123", "role": "faculty", "name": "Dr. Faculty", "id": "FAC_001", "faculty_id": "FAC_001", "department": "Computer Engineering"},
    "student@edusense.com": {"password": "student123", "role": "student", "name": "Demo Student", "id": "STU000001", "student_id": "STU000001", "department": "Computer Engineering", "semester": 5},
}

@router.post("/login")
def login(creds: LoginSchema):
    # Check demo accounts first
    if creds.email in DEMO_ACCOUNTS:
        demo = DEMO_ACCOUNTS[creds.email]
        if creds.password == demo["password"]:
            token = create_access_token({"sub": creds.email, "role": demo["role"]})
            return {
                "access_token": token,
                "token_type": "bearer",
                "user": {
                    "id": demo["id"],
                    "email": creds.email,
                    "name": demo["name"],
                    "role": demo["role"],
                    **{k: v for k, v in demo.items() if k not in ["password", "id", "name", "role"]}
                }
            }
        raise HTTPException(status_code=401, detail="Invalid credentials")

    # Firestore lookup for real users
    db = get_firestore()
    users = db.collection("users").where("email", "==", creds.email).limit(1).stream()
    user_doc = next(users, None)

    if not user_doc:
        raise HTTPException(status_code=401, detail="Invalid credentials")

    user = user_doc.to_dict()
    if not verify_password(creds.password, user.get("password", "")):
        raise HTTPException(status_code=401, detail="Invalid credentials")

    token = create_access_token({"sub": user.get("email"), "role": user.get("role")})

    return {
        "access_token": token,
        "token_type": "bearer",
        "user": {
            "id": user_doc.id,
            "email": user.get("email"),
            "name": user.get("name"),
            "role": user.get("role"),
        }
    }

@router.post("/signup")
def signup(data: SignupSchema):
    if data.role != "student":
        raise HTTPException(status_code=403, detail="Only students can sign up. Faculty accounts are generated by admins.")

    db = get_firestore()
    existing = db.collection("users").where("email", "==", data.email).limit(1).stream()
    if next(existing, None):
        raise HTTPException(status_code=400, detail="Email already registered")

    user_id = str(uuid.uuid4())
    db.collection("users").document(user_id).set(
        {
            "email": data.email,
            "password": get_password_hash(data.password),
            "name": data.name,
            "role": "student",
            "created_at": datetime.utcnow().isoformat(),
        }
    )

    return {"message": "User registered successfully"}
