version: '3.8'

services:
  db:
    image: postgres:15
    container_name: edusense_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: edusense
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: edusense_backend
    ports:
      - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_PASS=postgrespassword
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=edusense
      - JWT_SECRET=edusense_super_secret
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: edusense_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

  airflow:
    image: apache/airflow:2.9.1
    container_name: edusense_airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgrespassword@db:5432/edusense
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./etl_pipeline:/opt/airflow/etl_pipeline
      - ./backend:/opt/airflow/backend
    ports:
      - "8080:8080"
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@edusense.com && airflow scheduler & airflow webserver"
    depends_on:
      db:
        condition: service_healthy

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: edusense_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Kolkata
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - backend

volumes:
  pgdata:
  n8n_data:
